/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_lbb_kavosh_algorithm_JKavosh */

#ifndef _Included_edu_lbb_kavosh_algorithm_JKavosh
#define _Included_edu_lbb_kavosh_algorithm_JKavosh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_lbb_kavosh_algorithm_JKavosh
 * Method:    getCanonicalLabeling
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_lbb_kavosh_algorithm_JKavosh_getCanonicalLabeling
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
